[workspace]
members = ["common","bot","api"]

[workspace.package]
version = "1.0.1"
authors = ["ilotterytea <ilotterytea@pm.me>"]
edition = "2021"
publish = false
repository = "https://github.com/ilotterytea/bot"
