[workspace]
members = ["common", "bot", "api"]
resolver = "2"

[workspace.package]
version = "1.0.3"
authors = ["ilotterytea <me@ilotterytea.kz>"]
edition = "2024"
publish = false
repository = "https://github.com/ilotterytea/bot"
