version: '3.8'

services:
  db:
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_NAME: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgres:16.1-bullseye
    expose:
      - 5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h db -p 5432 -U ${POSTGRES_USER}"
        ]

  migration:
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./docker/migration.Dockerfile
    command: "diesel setup --database-url \"postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOSTNAME}/${POSTGRES_DB}\" --migration-dir \".\""
    env_file:
      - .env
    links:
      - db

  api:
    restart: on-failure
    depends_on:
      - db
      - migration
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    command: "cargo run --release --package api"
    env_file:
      - .env
    links:
      - db
    ports:
      - "8085:8085"

  twitch_bot:
    restart: on-failure
    depends_on:
      - db
      - migration
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    command: "cargo run --release --package bot"
    env_file:
      - .env
    links:
      - db

  web:
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    command: "npm start"
    env_file:
      - .env
    ports:
      - "3000:3000"
